project:
  type: website
  output-dir: docs

website:
  title: "LANDFIRE 101"
  sidebar: 
    style: "docked"
    search: true
    contents: auto
  body-footer: |
    # Still have questions? LANDFIRE is here to help.

    -   Ask the [LANDFIRE Helpdesk](mailto:helpdesk@landfire.gov?subject=landfirehelp) (email link).

    -   Search the [LANDFIRE Helpdesk Dashboard](https://landfire.gov/helpdesk) to see what others are asking and find solutions to common problems.

    -   Search and subscribe to the [LANDFIRE YouTube Channel](https://www.youtube.com/@LANDFIREvideo) (see tutorials, Office Hours, quick demonstrations).

    -   [Join an Office Hour](https://tnc.zoom.us/meeting/register/tJwvcOqopz4uHNbBBWNoFeLIHpdH8YFO7QLS) (monthly meeting with open format Q & A with LANDFIRE experts).

    -   [Schedule a meeting](mailto:landfire@tnc.org?subject=landfirehelp) (email link) with TNC’s LANDFIRE Team.
    
    
    # navbar:
  #   left:
  #     - text: Home
  #       href: index.qmd
  #     - text: What is LANDFIRE?
  #       href: what-is-landfire.qmd
  #     - text: LANDFIRE Data
  #       href: lf-data.qmd
  #       menu: 
  #         - text: Biophysical Settings
  #           href: bps.qmd
  #         - text: Existing Vegetation
  #           href: existing-veg.qmd
  #           
  # sidebar:
  #   - title: "Biophysical Settings"
  #     style: "docked"
  #     contents:
  #       - bps-spatial.qmd
  #       - bps-descriptions.qmd
  #       - bps-models.qmd
  #   - title: "Existing Vegetation"
  #     style: "docked"
  #     contents:
  #       - evt.qmd
  #       - evc.qmd
  #       - evh.qmd    
        
        
        
format:
  html:
    theme: 
      light: lumen
      dark: cyborg
    css: styles.css
    toc: false
    page-layout: full

editor: source

