project:
  type: website
  output-dir: docs

website:
  title: "LANDFIRE 101"
  sidebar: 
    style: "docked"
    search: true
    contents: auto
    
    
    # navbar:
  #   left:
  #     - text: Home
  #       href: index.qmd
  #     - text: What is LANDFIRE?
  #       href: what-is-landfire.qmd
  #     - text: LANDFIRE Data
  #       href: lf-data.qmd
  #       menu: 
  #         - text: Biophysical Settings
  #           href: bps.qmd
  #         - text: Existing Vegetation
  #           href: existing-veg.qmd
  #           
  # sidebar:
  #   - title: "Biophysical Settings"
  #     style: "docked"
  #     contents:
  #       - bps-spatial.qmd
  #       - bps-descriptions.qmd
  #       - bps-models.qmd
  #   - title: "Existing Vegetation"
  #     style: "docked"
  #     contents:
  #       - evt.qmd
  #       - evc.qmd
  #       - evh.qmd    
        
        
        
format:
  html:
    theme: cosmos
    css: styles.css
    toc: false
    page-layout: full

editor: source

