project:
  type: website
  output-dir: docs

website:
  title: "LANDFIRE 101"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: what-is-landfire.qmd
        text: What is LANDFIRE?

format:
  html:
    theme: cosmos
    css: styles.css
    toc: true
    page-layout: full

editor: source

