project:
  type: website
  output-dir: docs
  resources: 
    - assets/js/fix-accessibility.js


website:
  title: "LANDFIRE 101"
  page-navigation: true
  google-analytics: G-7HYRRL98N6
  sidebar: 
    style: "docked"
    search: true
    contents:
      - text: "LANDFIRE: an introduction"
        href: index.qmd
      - text: "An Overview of LANDFIRE Products"
        href: 1_what-is-landfire.qmd
      - text: "Explore LANDFIRE spatial data"
        href: 2_landfire-attributes.qmd
      - section: "LANDFIRE Vegetation Datasets"
        contents:
          - href: LANDFIRE_Datasets/1_Vegetation/1_lf-vegetation-data.qmd
          - section: "Biophysical Settings"
            href: LANDFIRE_Datasets/1_Vegetation/Biophysical_Settings/1-bps.qmd
            contents:
              - href: LANDFIRE_Datasets/1_Vegetation/Biophysical_Settings/1-bps.qmd
              - href: LANDFIRE_Datasets/1_Vegetation/Biophysical_Settings/2-bps_spatial.qmd
              - href: LANDFIRE_Datasets/1_Vegetation/Biophysical_Settings/3-bps_documents.qmd
              - href: LANDFIRE_Datasets/1_Vegetation/Biophysical_Settings/4-bps-models.qmd
              - href: LANDFIRE_Datasets/1_Vegetation/Biophysical_Settings/5-refcon-table.qmd
          - section: "Existing Vegetation"
            href: LANDFIRE_Datasets/1_Vegetation/Existing_Vegetation/1-existing-vegetation-type.qmd
            contents:
              - href: LANDFIRE_Datasets/1_Vegetation/Existing_Vegetation/1-existing-vegetation-type.qmd
              - href: LANDFIRE_Datasets/1_Vegetation/Existing_Vegetation/2-existing-vegetation-cover.qmd
              - href: LANDFIRE_Datasets/1_Vegetation/Existing_Vegetation/3-existing-vegetation-height.qmd
          - section: "Succession Class"
            href: LANDFIRE_Datasets/1_Vegetation/Succession_Class/1-succession-class.qmd
            contents:
              - href: LANDFIRE_Datasets/1_Vegetation/Succession_Class/1-succession-class.qmd
          - section: "Vegetation Departure"
            href: LANDFIRE_Datasets/1_Vegetation/Vegetation_Departure/1-vegetation-departure.qmd
            contents:
              - href: LANDFIRE_Datasets/1_Vegetation/Vegetation_Departure/1-vegetation-departure.qmd
      - section: "LANDFIRE Fuels Datasets"
        href: LANDFIRE_Datasets/2_Fuels/1_fuels.qmd
        contents:
          - href: LANDFIRE_Datasets/2_Fuels/1_fuels.qmd
      - section: "Ways to get LANDFIRE Data"
        href: Get_Data/1-ways-to-get-data.qmd
        contents:
          - href: Get_Data/1-ways-to-get-data.qmd
          # - href: Get_Data/2-LANDFIRE-map-viewer.qmd
          # - href: Get_Data/3-full-extent-mosaics.qmd
          # - href: Get_Data/4-LANDFIRE-data-streaming.qmd
          # - href: Get_Data/5-rlandfire.qmd

    
    
  body-footer: |
    # Still have questions? LANDFIRE is here to help.

    -   Ask the [LANDFIRE Helpdesk](mailto:helpdesk@landfire.gov?subject=landfirehelp) (email link).

    -   Search and subscribe to the [LANDFIRE YouTube Channel](https://www.youtube.com/@LANDFIREvideo) (see tutorials, Office Hours, quick demonstrations).

    -   [Join an Office Hour](https://tnc.zoom.us/meeting/register/tJArf-igqD8oE9S7qGDsOm7oeF7aZBJDMqBG#/registration) (monthly meeting with open format Q & A with LANDFIRE experts).

    -   [Schedule a meeting](mailto:landfire@tnc.org?subject=landfirehelp) (email link) with TNC’s LANDFIRE Team.
    
    
    # navbar:

format:
  html:
    theme: 
      light: [lumen, styles-light.scss]
      dark: [cyborg, styles-dark.scss]
    respect-user-color-scheme: true 
    include-after-body:
      text: |
        <script type="application/javascript" src="assets/js/fix-accessibility.js"></script>
    css: _layout.scss
    toc: false
    grid:
      sidebar-width: 300px
      body-width: 1000px
      margin-width: 200px
      gutter-width: 2.25rem

editor: source

