---
title: "LANDFIRE Vegetation Datasets: An Overview"
author: "Sarah Hagen"
toc: true
format: html
---

::: callout-note
For the most up-to-date information on each LANDFIRE data product, please view the individual product pages on the [LANDFIRE Program website](https://www.landfire.gov).
:::

In our work, we frequently utilize various vegetation and fire regime datasets to gain a deeper understanding of certain landscapes. For example, key datasets such as Biophysical Settings, Existing Vegetation, and Succession Class are integrated to create the Vegetation Departure product. Here, you’ll learn how to access and make good use of these datasets. We’ll walk you through how to download each one and share real-life examples of how they can be applied. We’ll also introduce you to other helpful tools that can improve your work.

# A word about vegetation classifications

LANDFIRE adopted NatureServe’s [Ecological Systems](https://www.natureserve.org/publications/ecological-systems-united-states) (ES) classification in 2004. At that time, it was the only consistent mid-scale, continent-wide classification available and its ecological foundation fit the needs of the project as designed. ES is currently used in the Existing Vegetation Type (EVT), Environmental Site Potential, and Biophysical Settings (BpS) spatial layers, as well as the Biophysical Settings Models and Descriptions products. 

In addition to Ecological Systems, the EVT layer incorporates additional classes to represent developed and agricultural land use classes. Three other classifications are provided as attributes of the EVT layer: National Vegetation Classification Group (NVCG), National Vegetation Classification Macrogroup (NVCM) and Society of American Foresters/Society of Range Management (SAF/SRM) Cover Type. The only classification that is directly mapped by LANDFIRE at the present time is ES. NVCG is provided as a separate spatial layer in LF2016. It was modeled separately from the ES in some parts of CONUS, and in some areas it was crosswalked from LF2016 ES. The SAF/SRM attribute was created using a crosswalk with ES. Since the National Vegetation Classification is hierarchical, NVCM is created by rolling-up NVCG into the next highest level of the classification.

# What you will find in this section

- A brief overview of some commonly used datasets

- How to download and access LANDFIRE datasets

- How these key LANDFIRE datasets are linked to one another
